/* MotoMod AI SQL Server bootstrap. Run in SSMS against a new MotoMod database. */
CREATE TABLE dbo.Users (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), Email NVARCHAR(320) NOT NULL UNIQUE,
  DisplayName NVARCHAR(80) NOT NULL, PasswordHash NVARCHAR(500) NOT NULL, Role NVARCHAR(20) NOT NULL DEFAULT 'MEMBER',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE TABLE dbo.Bikes (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Brand NVARCHAR(60) NOT NULL, Model NVARCHAR(80) NOT NULL,
  ModelYear SMALLINT NOT NULL, Style NVARCHAR(50) NOT NULL, PowerBhp DECIMAL(6,2) NOT NULL, TorqueNm DECIMAL(6,2) NULL,
  WeightKg DECIMAL(6,2) NOT NULL, ImageUrl NVARCHAR(1000) NULL, SourceUrl NVARCHAR(1000) NULL, ImageCredit NVARCHAR(500) NULL, SpecsJson NVARCHAR(MAX) NOT NULL DEFAULT '{}',
  CONSTRAINT UQ_Bikes UNIQUE (Brand, Model, ModelYear), CONSTRAINT CK_Bikes_SpecsJson CHECK (ISJSON(SpecsJson)=1)
);
CREATE TABLE dbo.Parts (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY, Brand NVARCHAR(60) NOT NULL, Name NVARCHAR(120) NOT NULL,
  Category NVARCHAR(30) NOT NULL, Price DECIMAL(12,2) NOT NULL, PowerGainBhp DECIMAL(6,2) NOT NULL DEFAULT 0,
  WeightChangeKg DECIMAL(6,2) NOT NULL DEFAULT 0, ImageUrl NVARCHAR(1000) NULL, SourceUrl NVARCHAR(1000) NULL, ImageCredit NVARCHAR(500) NULL, ConfigJson NVARCHAR(MAX) NOT NULL DEFAULT '{}',
  CONSTRAINT CK_Parts_ConfigJson CHECK (ISJSON(ConfigJson)=1)
);
CREATE TABLE dbo.PartFitments (PartId INT NOT NULL REFERENCES dbo.Parts(Id), BikeId INT NOT NULL REFERENCES dbo.Bikes(Id), PRIMARY KEY (PartId, BikeId));
CREATE TABLE dbo.SavedPlans (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), UserId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Users(Id),
  BikeId INT NOT NULL REFERENCES dbo.Bikes(Id), Name NVARCHAR(120) NOT NULL, Status NVARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  Prompt NVARCHAR(2000) NULL, ConfigJson NVARCHAR(MAX) NOT NULL, TotalCost DECIMAL(12,2) NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT CK_SavedPlans_ConfigJson CHECK (ISJSON(ConfigJson)=1)
);
CREATE TABLE dbo.ModificationRequests (Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), UserId UNIQUEIDENTIFIER NOT NULL REFERENCES dbo.Users(Id), PlanId UNIQUEIDENTIFIER NULL REFERENCES dbo.SavedPlans(Id), Prompt NVARCHAR(2000) NOT NULL, ResponseJson NVARCHAR(MAX) NULL, Status NVARCHAR(20) NOT NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE dbo.ServiceProviders (Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), Name NVARCHAR(120) NOT NULL, City NVARCHAR(80) NOT NULL, Rating DECIMAL(3,2) NULL, IsVerified BIT NOT NULL DEFAULT 0, SpecialtiesJson NVARCHAR(MAX) NOT NULL DEFAULT '[]', CONSTRAINT CK_ServiceProviders_SpecialtiesJson CHECK (ISJSON(SpecialtiesJson)=1));
CREATE INDEX IX_Bikes_Brand ON dbo.Bikes(Brand); CREATE INDEX IX_Parts_Category ON dbo.Parts(Category); CREATE INDEX IX_SavedPlans_User_Updated ON dbo.SavedPlans(UserId, UpdatedAt DESC);
GO
/* Enable encryption in production only after backup/key governance is configured:
   CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'use-a-vault-generated-secret';
   CREATE CERTIFICATE MotoModTdeCertificate WITH SUBJECT = 'MotoMod TDE';
   CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_256 ENCRYPTION BY SERVER CERTIFICATE MotoModTdeCertificate;
   ALTER DATABASE MotoMod SET ENCRYPTION ON; */
